name: Get Unity Activation File

on:
  workflow_dispatch:

jobs:
  requestActivationFile:
    name: Request Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
        with:
          unityVersion: 2022.3.62f2

      - name: Upload activation file
        uses: actions/upload-artifact@v3
        with:
          name: activation-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}